### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cache/radius_nyu.pt'

### ISSUE THREAD

**Issue by PineREN** [yanconglin/VanishingPoint_HoughTransform_GaussianSphere#2]
Hello,Thank you for your excellent work!
I use the pretrained model  on NYU to detect VPs from image "example_yud.jpg".
Have downed "checkpoint_latest.pth.tar" ,"sphere_neighbors_403_180_32768.npz" and "ht_240_320_403_180.npz".Put them into the dir and run demo.py.Then error!
```
#################### im2ht compiling ############################
#################### done! ############################
#################### ht2im compiling ############################
#################### done! ############################
#################### ht2sphere compiling ############################
#################### done! ############################
############# MultiscaleRadiusGraph ######################################
Traceback (most recent call last):
  File "C:\apine\projects\VanishingPoint_HoughTransform_GaussianSphere\demo.py", line 253, in <module>
    main()
  File "C:\apine\projects\VanishingPoint_HoughTransform_GaussianSphere\demo.py", line 168, in main
    model = vpd.models.VanishingNet(backbone, vote_ht_dict, vote_sphere_dict)
  File "C:\apine\projects\VanishingPoint_HoughTransform_GaussianSphere\vpd\models\vanishing_net.py", line 31, in __init__
    self.hsn = DGCN(nf=[M.num_channels, M.num_channels, M.num_channels, M.num_channels, M.num_channels], num_nodes=C.io.num_nodes, num_neighbors=C.io.num_neighbors)
  File "C:\apine\projects\VanishingPoint_HoughTransform_GaussianSphere\vpd\models\dgcn.py", line 76, in __init__
    xyz, edge_index = compute_edge() # edge_index: [2, num_nodes*num_neighbors]
  File "C:\apine\projects\VanishingPoint_HoughTransform_GaussianSphere\vpd\models\multiscale_radius_graph.py", line 56, in __call__
    with open(self.cache_file, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cache/radius_nyu.pt'
```
But I don't know the source of this file.

**Comment by yanconglin** [comment]
em, the problme is [there](https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/866ff4fb95e388ce0db9f52111f97cc88cb71dbb/vpd/models/dgcn.py#L75). Since the 'cache' folder does not exist,  the model throws an error. I have created a new folder 'cache' in the main directory, where 'radius_nyu.pt' is saved. If the  'radius_nyu.pt'  does not exist, [this function](https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/866ff4fb95e388ce0db9f52111f97cc88cb71dbb/vpd/models/dgcn.py#L75) will automatically compute it.  Sorry, my bad. Should work now.

**Comment by PineREN** [comment]
It works! Thank you very much for your prompt reply!
