### ISSUE TITLE
About fibonacci sample and polar coordinates

### ISSUE THREAD

**Issue by shifan-Z** [yanconglin/VanishingPoint_HoughTransform_GaussianSphere#4]
Thanks for posting your excellent code! I have some problems when reading the code.
1. could you please show me the formula of the Fibonacci lattice you uesd? I found one online, shown later,  but it doesn't match the code. Or maybe I have wrong understanding. 
![image](https://user-images.githubusercontent.com/54871708/190915297-15732ef6-ec88-4866-911e-dee182e405e3.png)
https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/0926733b1bd58531c0a50216017aa29a4cd18025/parameterization.py#L53-L62
3. In line 100, it seems that the code used $\rho=xsin\theta + ycos\theta$, which means the $\theta$ maybe the angle between the direction of $\rho$ and positive y-axis.(the direction of y-axis is the same as the height direction of a image)
https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/0926733b1bd58531c0a50216017aa29a4cd18025/parameterization.py#L100
But in line 142-153, the $\theta$ may be the  the angle between the direction of $\rho$ and positive x-axis. which one is right？
https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/0926733b1bd58531c0a50216017aa29a4cd18025/parameterization.py#L142-L153
4. should line 410 be: `   theta = opt.theta` and`   rho = opt.rho`
line 418 be : `mapping_ht, rho_res, theta_res = hough_transform(rows, cols, theta, rho)`? 
https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/0926733b1bd58531c0a50216017aa29a4cd18025/parameterization.py#L410-L436
5. what is the meaning and value of the variable "vote_index_ht", I can't find in the file. https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/0926733b1bd58531c0a50216017aa29a4cd18025/parameterization.py#L178-L188
Looking forward to your reply.

**Comment by yanconglin** [comment]
(1) Regarding the Fibanicci sampling: please refer to [this](https://stackoverflow.com/questions/9600801/evenly-distributing-n-points-on-a-sphere/44164075). NeurVPS uses a slightly different sampling (the constant bias term).

(2) Check [this tutorial on OpenGL](https://www.scratchapixel.com/lessons/3d-basic-rendering/perspective-and-orthographic-projection-matrix/building-basic-perspective-projection-matrix) and [to_pixel function in NerVPS](https://github.com/zhou13/neurvps/blob/4eec4ecd98eb7e5dddb82d1c4141d63087c74cf1/neurvps/models/vanishing_net.py#L178). It is indeed confusing. If I remember correctly (vaguely), y is pointing up in both cases.  Let me know if the confusion remains.

(3) I am afraid you are wrong.  The outputs are a list (array) of rhos/thetas used to sample a grid, rather than the rho_res or theta_res where "res" indicate resolution 

(4) em, it seems "vote_index_ht" should have been replaced by "mapping_ht". Before releasing code, I used a slightly different naming convention. Sorry for the confusion. The commented lines are for debug or visualization only.

**Comment by shifan-Z** [comment]
Thank you so much to be so patient. I have already understand the reply to question(1) and (4).
I still have some problems with question (2) and (3).   
（2）Sorry, I am still confused. In line 100, `coords` is [x,y], whose shape is $[rowls*cols]\times2,$ sin_cos is $[sin\theta, cos\theta]$, whose shape is $2\times180$. So the  `coords @ sin_cos` is $xsin\theta+ycos\theta$.  However, I thought that the  $\rho$ might be $\rho = xcos\theta +ysin\theta$. https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/0926733b1bd58531c0a50216017aa29a4cd18025/parameterization.py#L93-L100
（3）So because of the first appearance of the variable `theta_res` in function main is in line 410:  `theta_res = opt.theta_res`. Should the line484 to 485 be : `theta_res` and `rho_res` ? Otherwise these two variables are not defined.
https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/0926733b1bd58531c0a50216017aa29a4cd18025/parameterization.py#L408-L413
https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/0926733b1bd58531c0a50216017aa29a4cd18025/parameterization.py#L475-L490
Looking forward to your reply.

**Comment by yanconglin** [comment]
Regarding (3): I see. you are right. they are indeed typos.  Fixed now.  Many thanks!

**Comment by yanconglin** [comment]
> 

Regarding (4):  `coords = np.concatenate((coords_r[:,None], coords_w[:,None]), axis=1).astype(np.float32) `  is the concatenation of row indices and column indices, where row indices are y and  column indices are x.   

Hough Transform: rho = x cos + y sin.   In the code:  `vote_map = (coords @ sin_cos).astype(np.float32) `, which is rho = row_id * sin + col_id * cos, or equivalently rho = y sin + x cos.   

The (x-y) and (col-row) conversion is tricky there.  row/col differs from x/y (image plane vs Cartesian coordinate).

**Comment by shifan-Z** [comment]
Thank you so much. I got it !
